config/routes.rb
Rails.application.routes.draw do
  root "static#index"

  resources :farmers, only: [:index]
  resources :addresses, only: [:create, :new, :create, :update]

  get "cart",          to: "cart_items#index"
  post "cart_items",   to: "cart_items#create"
  patch "cart_items",  to: "cart_items#update"
  delete "cart_items", to: "cart_items#destroy"

  get "dashboard",    to: "users#show"

  get "login",        to: "sessions#new"
  post "login",       to: "sessions#create"
  delete "logout",    to: "sessions#destroy"

  post "notifications/notify", to: "notifications#notify"

  resources :users, except: [:delete, :put]
  resources :orders, only: [:create, :show, :index, :update]
  resources :charges

  resources :categories, only: [:index, :show] do
    resources :items, only: [:show, :index]
  end

  namespace :admin do
    resources :items, except: [:show, :index]
    resources :farmers, only: [:index, :update]
    get "dashboard",    to: "users#show"
    post "dashboard",    to: "users#update"
  end

  namespace :farmer_admin do
    resources :items
    resources :farmers, only: [:edit, :update]
    resources :users, only: [:new, :create, :update]
    get "dashboard",    to: "users#show"
    resources :orders, only: [:update]
  end

  namespace :farmers, path: ":farmer", as: :farmer do
    resources :items, only: [:index, :show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true,
    length: { in: 6..30 },
    format: { with:
      /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9._%+-]+.[a-zA-Z0-9._%+-]+\z/ }
  validates :last_name, :first_name, :phone_number, presence: true
  validates :farmer_id, presence: true, if: :farmer_admin?

  has_many :orders
  belongs_to :farmer
  has_one :address

  enum role: [ :guest, :user, :farmer_admin, :admin ]

  def name
    email.gsub(/@.*/, '').capitalize
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_address
    "#{address.street_address} #{address.apt} #{address.city}, " +
      "#{address.state} #{address.zip_code}"
  end

  def update_all(user_information)
    user_params, address_params = get_params(user_information)
    if update(user_params) && update_or_create_address(address_params)
      return true
    else
      return false
    end
  end

  def update_or_create_address(params)
    address ? address.update(params) : Address.create(params)
  end

    private

    def get_params(user_information)
      user_information = user_information.merge(user_id: id)
      informer = UserInformationWrapper.new(user_information)
      return informer.user_params, informer.address_params
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def show
    if session[:filter]
      @orders = Order.where(status: session[:filter]).order(:id)
    else
      @orders = Order.all.order(:id)
    end
  end

  def update
    session[:filter] = params[:filter]
    redirect_to admin_dashboard_path
  end
end

app/controllers/farmer_admin/users_controller.rb
class FarmerAdmin::UsersController < FarmerAdminController
  def show
    @farmer_admins = User.where(farmer: current_user.farmer.id)
    farmer = current_user.farmer
    @orders_data = FarmerAdminOrders.farmer_order_data(farmer)
  end

  def update
    if user = User.find_by(email: params[:user][:email])
      user.update(role: 2,
                  farmer_id: current_user.farmer.id) unless (user.admin? || user.farmer_admin?)
      flash[:notice] = "New Farmer Admin, #{user.name} Added for #{current_user.farmer.name}!"
      redirect_to farmer_admin_dashboard_path
    else
      flash[:errors] = "Couldn't find a user with that email"
      redirect_to new_farmer_admin_user_path
    end
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.valid?
      create_farmer_admin(user)
      flash[:notice] = "New Farmer Admin, #{user.name} Added for #{current_user.farmer.name}!"
      redirect_to farmer_admin_dashboard_path
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_farmer_admin_user_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :phone_number, :first_name,
        :last_name)
    end

    def create_farmer_admin(user)
      user.role = 2
      user.farmer_id = current_user.farmer.id
      user.save
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :show]
  before_action :verify_user, only: [:show, :edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path(id: @user.id)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
    @orders = @user.orders
  end

  def edit
  end

  def update
    if @user.update_all(user_and_address_params)
      redirect_to edit_user_path(current_user.id)
    else
      flash[:errors] = "Invalid input params"
      redirect_to edit_user_path(current_user.id)
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_and_address_params
    params.require(:user_and_address).permit(:email, :password, :phone_number,
      :first_name, :last_name, :street_address, :apt, :city, :state, :zip_code)
  end

  def user_params
    params.require(:user).permit(:email, :password, :phone_number, :first_name,
      :last_name)
  end

  def verify_user
    if current_user && current_user.id == params[:id].to_i
      true
    else
      render file: "#{Rails.root}/public/401.html", layout: false, status: 401
    end
  end
end

app/views/users/_address_form.html.erb
<div class="well">
<%= form_for :address, url: address_path(current_user.address.id), method: :patch do |f| %>
  <div class="form-group">
    <%= f.label "Street" %>
    <%= f.text_field :street_address, class: "form-control input-md", placeholder: current_user.address.street_address %>
  </div>
  <div class="form-group">
    <%= f.label "Apartment" %>
    <%= f.text_field :apt, class: "form-control input-md", placeholder: current_user.address.apt %>
  </div>
  <div class="form-group">
    <%= f.label "City" %>
    <%= f.text_field :city, class: "form-control input-md", placeholder:  current_user.address.city %>
  </div>
  <div class="form-group">
    <%= f.label "State" %>
    <%= f.text_field :state, class: "form-control input-md", placeholder:  current_user.address.state %>
  </div>
  <div class="form-group">
    <%= f.label "Zip Code" %>
    <%= f.text_field :zip_code, class: "form-control input-md", placeholder:  "#{current_user.address.zip_code}" %>
  </div>
    <%= f.submit "Update Address", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/_email_form.html.erb
<div class="well">
  <%= form_for :user_and_address, url: user_path, method: :patch do |f| %>
    <div class="form-group">
      <%= f.label "Email" %>
      <%= f.text_field :email, class: "form-control input-md", placeholder: "#{@user.email}" %>
    </div>
    <%= f.submit "Update Email", class: "btn btn-primary" %>
</div>
<% end %>

app/views/users/_name_form.html.erb
<div class="well">
  <%= form_for :user_and_address, url: user_path, method: :patch do |f| %>
    <div class="form-group">
      <%= f.label "First Name" %>
      <%= f.text_field :first_name, class: "form-control input-md", placeholder: "#{current_user.first_name}" %>
    </div>
    <div class="form-group">
      <%= f.label "Last Name" %>
      <%= f.text_field :last_name, class: "form-control input-md", placeholder: "#{current_user.last_name}" %>
    </div>
    <%= f.submit "Update Name", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/_password_form.html.erb
<div class="well">
<%= form_for :user_and_address, url: user_path, method: :patch do |f| %>
  <div class="form-group">
    <%= f.label "Password" %>
    <%= f.password_field :password, class: "form-control input-md", placeholder: "Enter New Password" %>
  </div>
  <!-- <div class="form-group">
    <%= f.password_field :password, class: "form-control input-md", placeholder: "Confirm New Password" %>
  </div> -->
    <%= f.submit "Update Password", class: "btn btn-primary" %>
</div>
<% end %>

app/views/users/_phone_number_form.html.erb
<div class="well">
  <%= form_for :user_and_address, url: user_path, method: :patch do |f| %>
    <div class="form-group">
      <%= f.label "Phone Number" %>
      <%= f.text_field :phone_number, class: "form-control input-md", placeholder: current_user.phone_number %>
    </div>
    <%= f.submit "Update Phone Number", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'heroic-features', media: 'all', 'data-turbolinks-track' => true %>

<div class="container">
<h1 id='profile'>Edit Profile</h1>
<h2><%= link_to "Back to Profile", user_path(current_user) %></h2> 
<br>
<%= render partial: "email_form" %>
<%= render partial: "name_form" %>
<%= render partial: "phone_number_form" %>
<%= render partial: "password_form" %>
<% if current_user.address %>
  <%= render partial: "address_form" %>
<% else %>
<div class="well">
  <h4><%= link_to("Add Address", new_address_path) %></h4>
</div>
<% end %>
</div>

app/views/users/new.html.erb
<div class="container text-center">


  <br>

  <div class="row">
    <div class="col-md-offset-4 col-md-4 well" id="login_form">
      <h2>Create Your Account</h2>
      <%= bootstrap_form_for @user do |f| %>
        <div class="form-group">
          <%= f.text_field :email %>
        </div>

        <div class="form-group">
          <%= f.password_field :password, icon: "lock" %>
        </div>

        <div class="form-group">
          <%= f.text_field :first_name %>
        </div>

        <div class="form-group">
          <%= f.text_field :last_name %>
        </div>

        <div class="form-group">
          <%= f.text_field :phone_number %>
        </div>

        <div class="form-group">
          <%= f.submit "Create Account", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'heroic-features', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Page Content -->
  <div class="container">

  <div class="row">
    <div class="col-lg-12 ">
      <h2>Hello <%= @user.email %></h1>
      <h3><%= link_to "Past Orders", orders_path %>
    </div>
  </div>

  <hr style="clear:both;"/>
  <br>

  <div class="row">
  <div class="col-md-4">
      <div class="well">
        <h2>Profile</h2>
        <h6><%= link_to "Edit Profile", edit_user_path(@user) %></h6>
        <hr>

        <h4>Full Name</h4>
        <%= @user.full_name %>
        <br>
        <br>

        <h4>Phone Number</h4>
        <%= number_to_phone(@user.phone_number, area_code: true) %>
        <br>
        <br>

        <h4>Address</h4>
        <% if @user.address %>
          <%= @user.address.street_address %>
          <%= @user.address.apt if @user.address.apt %>
          <br>
          <%= @user.address.city %>,
          <%= @user.address.state %>
          <%= @user.address.zip_code %>
        <% end %>
      </div>

  </div>

</div>
  <!-- /.container -->

  <!-- jQuery -->
  <script src="js/jquery.js"></script>

  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>