config/routes.rb
Rails.application.routes.draw do
  root "static#index"

  resources :farmers, only: [:index]
  resources :addresses, only: [:create, :new, :create, :update]

  get "cart",          to: "cart_items#index"
  post "cart_items",   to: "cart_items#create"
  patch "cart_items",  to: "cart_items#update"
  delete "cart_items", to: "cart_items#destroy"

  get "dashboard",    to: "users#show"

  get "login",        to: "sessions#new"
  post "login",       to: "sessions#create"
  delete "logout",    to: "sessions#destroy"

  post "notifications/notify", to: "notifications#notify"

  resources :users, except: [:delete, :put]
  resources :orders, only: [:create, :show, :index, :update]
  resources :charges

  resources :categories, only: [:index, :show] do
    resources :items, only: [:show, :index]
  end

  namespace :admin do
    resources :items, except: [:show, :index]
    resources :farmers, only: [:index, :update]
    get "dashboard",    to: "users#show"
    post "dashboard",    to: "users#update"
  end

  namespace :farmer_admin do
    resources :items
    resources :farmers, only: [:edit, :update]
    resources :users, only: [:new, :create, :update]
    get "dashboard",    to: "users#show"
    resources :orders, only: [:update]
  end

  namespace :farmers, path: ":farmer", as: :farmer do
    resources :items, only: [:index, :show]
  end
end

app/models/farmer.rb
class Farmer < ActiveRecord::Base
  has_many :items
  has_many :users

  has_many :farmer_orders
  has_many :orders, through: :farmer_orders

  validates :slug, presence: true, uniqueness: true,
            length: { in: 6..30 }

  before_validation :generate_slug

  def generate_slug
    self.slug = name.parameterize if name
  end
end

app/controllers/admin/farmers_controller.rb
class Admin::FarmersController < AdminController

  def index
    @farmers = Farmer.all
  end

  def update
    farmer = Farmer.find(params[:id])
    farmer.update(farmer_params)
    flash[:notice] = "Updated #{farmer.name}'s status"
    redirect_to admin_farmers_path
  end

  private

  def farmer_params
    params.permit(:active)
  end

end

app/controllers/farmer_admin/farmers_controller.rb
class FarmerAdmin::FarmersController < FarmerAdminController
  def edit
    @farmer = Farmer.find(current_user.farmer.id)
  end

  def update
    @farmer = Farmer.find(current_user.farmer.id)
    if @farmer.update(farmer_params)
      flash[:notice] = "Successfully updated informaiton"
      redirect_to farmer_admin_dashboard_path
    else
      flash[:errors] = @farmer.errors.full_messages
      redirect_to edit_farmer_admin_farmer_path
    end
  end

  private

  def farmer_params
    params.require(:farmer).permit(:name, :image_url)
  end
end

app/controllers/farmers/farmers_base_controller.rb
class Farmers::FarmersBaseController < ApplicationController
  helper_method :current_farmer

  def current_farmer
    @current_farmer ||= Farmer.find_by(slug: params[:farmer])
  end
end

app/controllers/farmers/items_controller.rb
class Farmers::ItemsController < Farmers::FarmersBaseController
  def index
    if current_farmer.active?
      @items = current_farmer.items
    else
      flash[:errors] = "Farm not active!"
      redirect_to farmers_path
    end
  end
end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
  def index
    @farmers = Farmer.where(active: true)
  end
end

app/views/admin/farmers/_farmer.html.erb
<div id="<%= farmer.name %>">
  <tr>
    <td><h3><%= link_to farmer.name, farmer_items_path(farmer) %></h3></td>
      <% if farmer.active? %>
          <td class="text-center">
            <h3>Active</h3>
          </td>
          <td class="text-center">
            <%= link_to "Deactivate", admin_farmer_path(farmer, active: false),
            method: :patch, class: "btn btn-danger" %>
          </td>
          <% else %>
          <td class="text-center">
            <h3>Inactive</h3>
          </td>
          <td class="text-center">
            <%= link_to "Activate", admin_farmer_path(farmer, active: true),
            method: :patch, class: "btn btn-success" %>
          </td>
      <% end %>
  </tr>
</div>

app/views/admin/farmers/index.html.erb
<div class="container">
  <div id="page-wrapper">
    <div class="container-fluid">
      <div class="row">
      <div class="col-lg-12 text-center">
          <h1 id="page-header">Manage Farms</h1>
      </div>
      <div class="col-lg-12 text-center">
        <h2><%= link_to("Back to Dashboard", admin_dashboard_path) %></h2>
        <hr>
      </div>
      <h2>Farms</h2>
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Current Status</th>
                            <th>Update Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <%= render partial: "farmer", collection: @farmers %>
                    </tbody>
                </table>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>