config/routes.rb
Rails.application.routes.draw do
  root "static#index"

  resources :farmers, only: [:index]
  resources :addresses, only: [:create, :new, :create, :update]

  get "cart",          to: "cart_items#index"
  post "cart_items",   to: "cart_items#create"
  patch "cart_items",  to: "cart_items#update"
  delete "cart_items", to: "cart_items#destroy"

  get "dashboard",    to: "users#show"

  get "login",        to: "sessions#new"
  post "login",       to: "sessions#create"
  delete "logout",    to: "sessions#destroy"

  post "notifications/notify", to: "notifications#notify"

  resources :users, except: [:delete, :put]
  resources :orders, only: [:create, :show, :index, :update]
  resources :charges

  resources :categories, only: [:index, :show] do
    resources :items, only: [:show, :index]
  end

  namespace :admin do
    resources :items, except: [:show, :index]
    resources :farmers, only: [:index, :update]
    get "dashboard",    to: "users#show"
    post "dashboard",    to: "users#update"
  end

  namespace :farmer_admin do
    resources :items
    resources :farmers, only: [:edit, :update]
    resources :users, only: [:new, :create, :update]
    get "dashboard",    to: "users#show"
    resources :orders, only: [:update]
  end

  namespace :farmers, path: ":farmer", as: :farmer do
    resources :items, only: [:index, :show]
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  validates :name, presence: true,
    length: { in: 3..30 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @items = @category.items.joins(:farmer).where('farmers.active')
  end

end

app/views/categories/_carousel.html.erb
<%= stylesheet_link_tag 'modern-business', media: 'all', 'data-turbolinks-track' => true %>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Modern Business - Start Bootstrap Template</title>

    <link href="css/modern-business.css" rel="stylesheet">

    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

</head>

<body>

    <!-- Header Carousel -->
    <header id="myCarousel" class="carousel slide" style="margin:0 auto">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <div class="fill" style="background-image:url('http://food.ogjenn.com/wp-content/uploads/2014/11/NCFC-Food-Image-2000x600.jpg');"></div>
                <div class="carousel-caption">
                    <h2></h2>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('http://ethnicfoodshow.com/wp-content/uploads/2015/04/chleb.jpg');"></div>
                <div class="carousel-caption">
                    <h2></h2>
                </div>
            </div>
            <div class="item">
                <div class="fill" style="background-image:url('http://www.quakervalleyfoods.com/wp-content/uploads/2014/03/provisions_resize.jpg');"></div>
                <div class="carousel-caption">
                    <h2></h2>
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>
    </header>
</body>

</html>

app/views/categories/index.html.erb
<%= stylesheet_link_tag 'heroic-features', media: 'all', 'data-turbolinks-track' => true %>

      <%= render partial: "carousel" %>
    <hr>
    <!-- Categories -->
  <div class="container">
    <div class="row">
    <% @categories.each do |category| %>
      <div class="col-sm-4">
          <div class="thumbnail">
              <img src=<%= category.image_url %> alt="">
              <div class="caption text-center">
                  <h2><%= link_to category.name, category_path(category.id) %></h2>
              </div>
          </div>
      </div>
    <% end %>
    </div>
    <div class="col-md-offset-4 col-md-4 btn-lg text-center">
      <%= link_to "Farmers", farmers_path, class: "btn btn-primary" %>
    </div>
  </div>
<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<!-- Script to Activate the Carousel -->
<script>
$('.carousel').carousel({
    interval: 3000 //changes the speed
})
</script>

app/views/categories/show.html.erb
<%= stylesheet_link_tag 'heroic-features', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Page Content -->
<div class="container">

  <header id='categories'>

  <hr>

  <div class = "row">
    <div class="col-md-12 text-center">
      <h1><%= @category.name %></h1>
    </div>
  </div>
    <div class="row">
      <div class="col-lg-12">
        <% if farmer_admin_authorized? %>
          <p><%= link_to "Add Item", new_farmer_admin_item_path(@item, category_id: @category.id), class: "btn btn-primary" %></p>
        <% end %>
      </div>
    </div>
  </header>

  <hr>

  <!-- Items -->
  <div class = "row">
  <% @items.each do |item| %>
    <div class="col-sm-4">
      <div class="thumbnail caption text-center">
        <img src=<%= item.image_url %> alt="">
        <h3><%= link_to item.name, category_item_path(@category.id, item.id) %></h3>
        <p>Offered by <%= item.farmer.name %></p>
        <p><%= item.description %></p>
        <h4><%= number_to_currency(item.price) %></h4>
        <p>
          <%= button_to "Add #{item.name}" , cart_items_path(item_id: item.id), class: "btn btn-primary outline" %>
        </p>
          <% if current_user && current_user.admin? %>
            <%= link_to "Edit Item", edit_admin_item_path(item) %>
            <%= link_to "Delete Item", admin_item_path(item), method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>

          <% if farmer_admin_authorized? && current_user.farmer.id == item.farmer.id %>
            <%= link_to "Edit", edit_farmer_admin_item_path(item) %>
            <%= link_to "Delete", farmer_admin_item_path(item, category_id:
              item.category.id), method: :delete %>
          <% else %>
            <br>
          <% end %>
      </div>
      </div>
  <% end %>
</div>
  <div class = "row">
    <div class = "col-md-offset-4 col-md-4 text-center">
      <h3><%= link_to "Categories", categories_path, class: "btn btn-lg btn-primary" %></h3>
      </div>
  </div>
</div>