config/routes.rb
Rails.application.routes.draw do
  root "static#index"

  resources :farmers, only: [:index]
  resources :addresses, only: [:create, :new, :create, :update]

  get "cart",          to: "cart_items#index"
  post "cart_items",   to: "cart_items#create"
  patch "cart_items",  to: "cart_items#update"
  delete "cart_items", to: "cart_items#destroy"

  get "dashboard",    to: "users#show"

  get "login",        to: "sessions#new"
  post "login",       to: "sessions#create"
  delete "logout",    to: "sessions#destroy"

  post "notifications/notify", to: "notifications#notify"

  resources :users, except: [:delete, :put]
  resources :orders, only: [:create, :show, :index, :update]
  resources :charges

  resources :categories, only: [:index, :show] do
    resources :items, only: [:show, :index]
  end

  namespace :admin do
    resources :items, except: [:show, :index]
    resources :farmers, only: [:index, :update]
    get "dashboard",    to: "users#show"
    post "dashboard",    to: "users#update"
  end

  namespace :farmer_admin do
    resources :items
    resources :farmers, only: [:edit, :update]
    resources :users, only: [:new, :create, :update]
    get "dashboard",    to: "users#show"
    resources :orders, only: [:update]
  end

  namespace :farmers, path: ":farmer", as: :farmer do
    resources :items, only: [:index, :show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true,
    length: { in: 6..30 },
    format: { with:
      /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9._%+-]+.[a-zA-Z0-9._%+-]+\z/ }
  validates :last_name, :first_name, :phone_number, presence: true
  validates :farmer_id, presence: true, if: :farmer_admin?

  has_many :orders
  belongs_to :farmer
  has_one :address

  enum role: [ :guest, :user, :farmer_admin, :admin ]

  def name
    email.gsub(/@.*/, '').capitalize
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_address
    "#{address.street_address} #{address.apt} #{address.city}, " +
      "#{address.state} #{address.zip_code}"
  end

  def update_all(user_information)
    user_params, address_params = get_params(user_information)
    if update(user_params) && update_or_create_address(address_params)
      return true
    else
      return false
    end
  end

  def update_or_create_address(params)
    address ? address.update(params) : Address.create(params)
  end

    private

    def get_params(user_information)
      user_information = user_information.merge(user_id: id)
      informer = UserInformationWrapper.new(user_information)
      return informer.user_params, informer.address_params
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def show
    if session[:filter]
      @orders = Order.where(status: session[:filter]).order(:id)
    else
      @orders = Order.all.order(:id)
    end
  end

  def update
    session[:filter] = params[:filter]
    redirect_to admin_dashboard_path
  end
end

app/controllers/farmer_admin/users_controller.rb
class FarmerAdmin::UsersController < FarmerAdminController
  def show
    @farmer_admins = User.where(farmer: current_user.farmer.id)
    farmer = current_user.farmer
    @orders_data = FarmerAdminOrders.farmer_order_data(farmer)
  end

  def update
    if user = User.find_by(email: params[:user][:email])
      user.update(role: 2,
                  farmer_id: current_user.farmer.id) unless (user.admin? || user.farmer_admin?)
      flash[:notice] = "New Farmer Admin, #{user.name} Added for #{current_user.farmer.name}!"
      redirect_to farmer_admin_dashboard_path
    else
      flash[:errors] = "Couldn't find a user with that email"
      redirect_to new_farmer_admin_user_path
    end
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.valid?
      create_farmer_admin(user)
      flash[:notice] = "New Farmer Admin, #{user.name} Added for #{current_user.farmer.name}!"
      redirect_to farmer_admin_dashboard_path
    else
      flash[:errors] = user.errors.full_messages
      redirect_to new_farmer_admin_user_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :phone_number, :first_name,
        :last_name)
    end

    def create_farmer_admin(user)
      user.role = 2
      user.farmer_id = current_user.farmer.id
      user.save
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :show]
  before_action :verify_user, only: [:show, :edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path(id: @user.id)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
    @orders = @user.orders
  end

  def edit
  end

  def update
    if @user.update_all(user_and_address_params)
      redirect_to edit_user_path(current_user.id)
    else
      flash[:errors] = "Invalid input params"
      redirect_to edit_user_path(current_user.id)
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_and_address_params
    params.require(:user_and_address).permit(:email, :password, :phone_number,
      :first_name, :last_name, :street_address, :apt, :city, :state, :zip_code)
  end

  def user_params
    params.require(:user).permit(:email, :password, :phone_number, :first_name,
      :last_name)
  end

  def verify_user
    if current_user && current_user.id == params[:id].to_i
      true
    else
      render file: "#{Rails.root}/public/401.html", layout: false, status: 401
    end
  end
end

app/views/admin/users/_order.html.erb
<div id="order_<%= order.id %>">
  <tr>
    <td><%= link_to "Order ID: #{order.id}", order_path(order) %></td>
    <td><%= "#{order.created_at}" %></td>
    <td><%= order.total_price %></td>
    <td class="text-center">
      <% DashboardFormatter.new(order).find_links.each do |link| %>
        <%= link_to link[0], order_path(order, status:
          link[1]), method: :patch, class: "btn btn-danger" %>
      <% end %>
    </td>
  </tr>
</div>

app/views/admin/users/show.html.erb
<head>
    <link href="css/sb-admin.css" rel="stylesheet">
    <link href="css/plugins/morris.css" rel="stylesheet">
</head>

<body>

  <div class="container">
      <div id="page-wrapper">
          <div class="container-fluid">
              <div class="row">
                  <div class="col-lg-12">
                      <h1 id="page-header">
                          Dashboard <small>Statistics Overview</small>
                      </h1>
                  </div>
              </div>
              <div class="row">
                  <div class="col-lg-8 col-md-4 text-center">
                    <h2 class="order-filter"><%= link_to("All Orders", admin_dashboard_path(filter: nil), method: :post) %></h2>
                    <hr>
                  </div>
                <div class="col-lg-4">
                  <h2 class="text-center">Tasks</h2>
                  <hr>
                </div>
              </div>
              </br>
              <div class="row">
                  <div class="col-lg-2 col-md-4">
                      <div class="panel panel-yellow">
                          <div class="panel-heading">
                              <div class="row">
                                <%= link_to(admin_dashboard_path(filter: 0), method: :post) do %>
                                  <div class="col-md-12 ">
                                    <h4 class="order-filter"><%= "Ordered: #{DashboardFormatter.ordered?}" %></h4>
                                  </div>
                                <% end %>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="col-lg-2 col-md-4">
                      <div class="panel panel-primary">
                          <div class="panel-heading">
                              <div class="row">
                                <%= link_to(admin_dashboard_path(filter: 1), method: :post) do %>
                                  <div class="col-md-12 ">
                                    <h4 class="order-filter"><%= "Paid: #{DashboardFormatter.paid?}" %></h4>
                                  </div>
                                <% end %>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="col-lg-2 col-md-4">
                      <div class="panel panel-red">
                          <div class="panel-heading">
                              <div class="row">
                                <%= link_to(admin_dashboard_path(filter: 2), method: :post) do %>
                                  <div class="col-md-12 ">
                                    <h4 class="order-filter"><%= "Cancelled: #{DashboardFormatter.cancelled?}" %></h4>
                                  </div>
                                <% end %>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="col-lg-2 col-md-4">
                      <div class="panel panel-green">
                          <div class="panel-heading">
                              <div class="row">
                                <%= link_to(admin_dashboard_path(filter: 3), method: :post) do %>
                                  <div class="col-md-12 ">
                                    <h4 class="order-filter"><%= "Completed: #{DashboardFormatter.completed?}" %></h4>
                                  </div>
                                <% end %>
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="text-center">
                      <h4><%= link_to("Manage Farms", admin_farmers_path) %></h4>
                  </div>
              </div>
              <br>
              <h2>Orders</h2>
                  <div class="col-lg-12">
                      <div class="table-responsive">
                          <table class="table table-bordered table-hover table-striped">
                              <thead>
                                  <tr>
                                      <th>Order #</th>
                                      <th>Order Date</th>
                                      <th>Order Total</th>
                                      <th>Change Order Status</th>
                                  </tr>
                              </thead>
                              <tbody>
                                  <%= render partial: "order", collection: @orders %>
                              </tbody>
                          </table>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>

    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/plugins/morris/raphael.min.js"></script>
    <script src="js/plugins/morris/morris.min.js"></script>
    <script src="js/plugins/morris/morris-data.js"></script>

</body>